### model
model_name_or_path: Qwen/Qwen2.5-Coder-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: GraphCopilot_plus
template: qwen
cutoff_len: 5000
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3.1-8b/full/GraphCopilot_plus_v1
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 3.0e-5
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500
